#docker-compose for delab framework
name: delab 

services:
  delab_analytics:
    build: 
      context: ./delab_analytics/
      dockerfile: Dockerfile
    container_name: delab_analytics
    image: delab/analytics
    hostname: delab_analytics
    restart: unless-stopped
    ports: 
      - 8840:8840
    env_file:
      - .env
    environment:
      - NLTK_DATA=/root/nltk_data/
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - delab

  delab_llm: 
    build: 
      context: ./delab_llm/
      dockerfile: Dockerfile
    container_name: delab_llm
    image: delab/llm
    hostname: delab_llm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - LLAMA_ARG_MODEL=models/${LLM_MODEL}
      - LLAMA_ARG_PORT=8000
    networks: 
      - delab

networks:
  delab:
    driver: bridge