#docker-compose for delab framework

services:

  #llm module GPU
  delab_llm_gpu: 
    build: 
      context: delab_llm/gpu
      dockerfile: Dockerfile
    container_name: llm_gpu
    image: delab/llm_gpu
    profiles: 
      - gpu
    restart: unless-stopped
    ports: 
      - 3000:8000
    env_file:
      - .env
    environment:
      - USE_MLOCK=0 #do not keep the model in RAM
      - MODEL=/var/model/${LLM_MODEL}
    volumes: 
      - ./../models:/var/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu


  #llm module CPU
  delab_llm_cpu: 
    build: 
      context: delab_llm/cpu
      dockerfile: Dockerfile
    container_name: llm_cpu
    image: delab/llm_cpu
    profiles: 
      - cpu
    restart: unless-stopped
    ports: 
      - 3000:8000
    env_file:
      - .env
    environment:
      - USE_MLOCK=0 #do not keep the model in RAM
      - MODEL=/var/model/${LLM_MODEL}
    volumes: 
      - ./../models:/var/model

